### 주문 생성
POST localhost:9000/api/v1/orders
Content-Type: application/json

{
  "memberId": 10542,
  "orderItems": [
    {
      "itemCategory": "book",
      "itemName": "Spring Guide 2.0"
    },
    {
      "itemCategory": "book",
      "itemName": "Hibernate Core Principle"
    }
  ],
  "orderPayments": [
    {
      "paymentMethod": "CARD",
      "price": "20000.0000"
    },
    {
      "paymentMethod": "CARD",
      "price": "15000.0000"
    }
  ]
}

### 주문 '완료' 상태로 변경
PATCH localhost:9000/api/v1/orders/1?status=COMPLETE
