server:
  port: 9001
  tomcat:
    mbeanregistry:
      enabled: true # tomcat 과 관련된 메트릭 정보를 상세하게 알 수 있다.
    threads:
      min-spare: 20
      max: 150

spring:
  profiles:
    active: develop

  output:
    ansi:
      enabled: always

  post:
    redis:
      enable: true

  feed:
    redis:
      enable: true

resilience4j:
  ratelimiter:
    #    configs:
    #      default:
    #       registerHealthIndicator: false # actuator를 통해 ratelimiter 상태를 체크하기 위한 여부
    #       allowHealthIndicatorToFail: false
    #       subscribeForEvents: true
    #       eventConsumerBufferSize: 50
    instances:
      findPostsRefreshTimelineUsecase:
        limitForPeriod: 3000 # limitRefreshPeriod 기간 동안 허용되는 요청 수
        limitRefreshPeriod: 1s # limitRefresh 기간 (초)
        timeoutDuration: 3s # 권한 acquire(허가)를 위해 스레드가 대기하는 시간 (초)
      findPostsTimelineUsecase:
        limitForPeriod: 3000
        limitRefreshPeriod: 1s
        timeoutDuration: 3s
      findPostsUsecase:
        limitForPeriod: 3000
        limitRefreshPeriod: 1s
        timeoutDuration: 3s
      findPostUsecase:
        limitForPeriod: 3000
        limitRefreshPeriod: 1s
        timeoutDuration: 3s

management:
  endpoint:
    health:
      show-details: always # 상세하게 보고 싶을때
  #      show-components: always # UP, DOWN 상태만 보고 싶을때
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: develop

---
spring:
  config:
    activate:
      on-profile: production
