server:
  port: 9001
  tomcat:
    threads:
      min-spare: 20
      max: 100

spring:
  profiles:
    active: develop

  post:
    redis:
      enable: true

  feed:
    redis:
      enable: true

---
spring:
  config:
    activate:
      on-profile: develop

---
spring:
  config:
    activate:
      on-profile: production
