server:
  port: 9002
  tomcat:
    threads:
      min-spare: 10
      max: 10

spring:
  profiles:
    active: develop

---
spring:
  config:
    activate:
      on-profile: develop

  kafka:
    consumer:
      bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
      auto-offset-reset: latest # 가장 마지막 오프셋 값
      session-timeout: 30000 # 30초
      heartbeat-interval: 10000 # 10초
      max-poll-interval: 600000 # 10분
      max-poll-records: 250 # 최대 250개
      allow-auto-create-topics: false # 토픽 자동 생성 X
      group-id: sns-feed-event-worker
    topics:
      feed: feed-topic

  feed:
    redis:
      enable: true

---
spring:
  config:
    activate:
      on-profile: production

  kafka:
    consumer:
      bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
      auto-offset-reset: latest # 가장 마지막 오프셋 값
      session-timeout: 120000 # 2분 (120초)
      heartbeat-interval: 40000 # 40초, 그룹 코디네이터와 하트비트 인터벌 시간이며, session.timeout.ms보다 낮게 설정해야 함 (1/3 수준으로)
      max-poll-interval: 600000 # 10분 (600초)
      max-poll-records: 250 # 최대 250개
      allow-auto-create-topics: false # 토픽 자동 생성 X
      group-id: sns-feed-event-worker
    topics:
      feed: feed-topic

  feed:
    redis:
      enable: true
