spring:
  profiles:
    active: develop

---
spring:
  config:
    activate:
      on-profile: develop

  post:
    redis:
      mode: standalone
      nodes: localhost:6383

  feed:
    redis:
      mode: standalone
      nodes: localhost:6384

logging:
  level:
    io.lettuce.core.protocol.CommandHandler: debug

---
spring:
  config:
    activate:
      on-profile: production

  post:
    redis:
      mode: standalone
      nodes: localhost:6383

  feed:
    redis:
      mode: standalone
      nodes: localhost:6384
