server:
  port: 9001

spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      nodes:
        server-1: localhost:6379
        server-2: localhost:6380
        server-3: localhost:6381

logging:
  level:
    org.springframework.r2dbc: debug
    io.lettuce.core: debug

---
spring:
  config:
    activate:
      on-profile: prod

  r2dbc:
    pool:
      protocol: mysql
      write:
        host: localhost
        port: 9770
        user: masteruser
        password: masterpassword
        database: large-scale-system
        initial-pool-size: 10
        max-pool-size: 10
        max-life-time: 18000000 # 5 hour
        max-acquire-time: 5000 # 5 second
      read:
        host: localhost
        port: 9771
        user: slaveuser
        password: slavepassword
        database: large-scale-system
        initial-pool-size: 20
        max-pool-size: 20
        max-life-time: 18000000 # 5 hour
        max-acquire-time: 5000 # 5 second

  data:
    redis:
      standalone:
        nodes:
          server-1: localhost:6379
          server-2: localhost:6380
          server-3: localhost:6381
      cluster:
        nodes:
          server-1: localhost:6379
