server:
  port: 9002
  tomcat:
    threads:
      min-spare: 10
      max: 10

---
spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      feed:
        mode: standalone
        nodes:
          node1: localhost:6384

  kafka:
    consumer:
      bootstrap-servers: localhost:19093,localhost:29093,localhost:39093
      auto-offset-reset: latest # 가장 마지막 오프셋 값
      session-timeout: 30000 # 30초
      heartbeat-interval: 10000 # 10초
      max-poll-interval: 600000 # 10분
      max-poll-records: 250 # 최대 250개
      allow-auto-create-topics: false # 토픽 자동 생성 X

data:
  enable:
    redis:
      feed: true

---
spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      feed:
        mode: standalone
        nodes:
          node1: localhost:6384

  kafka:
    consumer:
      bootstrap-servers: localhost:19093,localhost:29093,localhost:39093
      auto-offset-reset: latest # 가장 마지막 오프셋 값
      session-timeout: 30000 # 30초
      heartbeat-interval: 10000 # 10초
      max-poll-interval: 600000 # 10분
      max-poll-records: 250 # 최대 250개
      allow-auto-create-topics: false # 토픽 자동 생성 X

data:
  enable:
    redis:
      feed: true
