server:
  tomcat:
    threads:
      min-spare: 20
      max: 100

spring:
  profiles:
    active: dev

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:issue-service
      username: sa

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.orm.jpa: debug
