spring:
  profiles:
    active: dev

  batch:
    # program arguments로 job name이 넘어오면, 해당 값과 일치하는 job만 실행하겠다는 의미
    job:
      # job.name이 있으면, job.name 값을 할당하고, 없으면 NONE을 할당하겠다는 의미
      # NONE이 할당되면, 어떤 배치도 실행하지 않겠다는 의미이다.
      # 즉, 혹시라도 값이 없을때 모든 배치가 실행되지 않도록 막는 역할이다.
      names: ${job.name:NONE}

data:
  enable:
    datasource: true
    jpa: true

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    open-in-view: false

infrastructure:
  enable:
    kafka:
      producer:
        coupon: true

---
spring:
  config:
    activate:
      on-profile: dev

  batch:
    chunk-size: 1000

data:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:dev-db
      username: sa

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create

infrastructure:
  kafka:
    producer:
      bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
      acks: 1
      buffer-memory: 33554432 # 33MB (default)
      compression-type: lz4
      retries: 0
      batch-size: 100000 # 100KB
      linger-ms: 50
      request-timeout-ms: 60000 # 60초
      delivery-timeout-ms: 120000 # 120초
      instance-id: producer-coupon-issued
    topics:
      coupon-issued: coupon-issued-topic

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.orm.jpa: debug

---
spring:
  config:
    activate:
      on-profile: prod

  batch:
    chunk-size: 1000

data:
  datasource:
    hikari:
      write:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://masteruser:masterpassword@localhost:9770/large-scale-system?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        minimum-idle: 50
        maximum-pool-size: 50
        max-lifetime: 18000000 # 5 hour
        connection-timeout: 5000 # 5 second
      read:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://slaveuser:slavepassword@localhost:9771/large-scale-system?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        minimum-idle: 50
        maximum-pool-size: 50
        max-lifetime: 18000000 # 5 hour
        connection-timeout: 5000 # 5 second

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

infrastructure:
  kafka:
    producer:
      bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
      acks: 1
      buffer-memory: 33554432 # 33MB (default)
      compression-type: lz4
      retries: 0
      batch-size: 1000 # 1KB, 해당 사이즈에 도달하게 되면, 메시지들을 전송한다.
      linger-ms: 500 # batch-size 값에 도달하지 못한 상황에서 linger.ms 제한 시간에 도달 했을때, 메시지들을 전송한다.
      request-timeout-ms: 120000 # 120초
      delivery-timeout-ms: 300000 # 300초
      instance-id: producer-coupon-issued
    topics:
      coupon-issued: coupon-issued-topic
