spring:
  profiles:
    active: develop

  batch:
    # program arguments로 job name이 넘어오면, 해당 값과 일치하는 job만 실행하겠다는 의미
    job:
      # job.name이 있으면, job.name 값을 할당하고, 없으면 NONE을 할당하겠다는 의미
      # NONE이 할당되면, 어떤 배치도 실행하지 않겠다는 의미이다.
      # 즉, 혹시라도 값이 없을때 모든 배치가 실행되지 않도록 막는 역할이다.
      names: ${job.name:NONE}

  wish:
    redis:
      enable: true

---
spring:
  config:
    activate:
      on-profile: develop

---
spring:
  config:
    activate:
      on-profile: production

